#!/bin/bash

npx hardhat compile

npx hardhat run scripts/deploy.js --network localhost

rm ../poker-ui/src/artifacts/Poker.json

cp ./artifacts/contracts/poker.sol/Poker.json ../poker-ui/src/artifacts/
